name: Node.js Package

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: apps/cli/dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: apps/cli/dist
      - name: Publish dlxx
        run: |
          cd apps/cli
          pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
